### ISSUE TITLE
Please wait…

### ISSUE THREAD

**Issue by ecub** [mohammad1ta/maceelight#1]
Hey. I compiled ur app, but it says "please wait" and nothing else happens. I think I may have done something wrong. Could u write an instruction?

I just turned on LAN in yeelight app settings and nothing more.

**Comment by mohammad1ta** [comment]
Dear ecub,
Thank you for testing this app.

It may be a conflict with turned on VPN or proxy. If you use it, please turn off and test it again.

If your problem was not solved, please debug it and share your results here:
Open **assets/scripts/main.js** and add the following code in _line 158_:
```js
console.log(reg);
```
Then run the app with **npm start**.
